services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "on-failure"
    environment:
      - APP_PORT=${APP_PORT}
      - APP_DEBUG=${APP_DEBUG}
      - APP_OS=${APP_OS}
      - APP_BASIC_AUTH=${WA_USER}:${WA_PASSWORD}
      - WHATSAPP_ACCOUNT_VALIDATION=${APP_ACCOUNT_VALIDATION}
    ports:
      - "${APP_PORT}:${APP_PORT}"