services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "on-failure"
    ports:
      - "3081:3000"